apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-cloud-db
  name: mongo-cloud-db-connection-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32000
  selector:
    app: mongo-cloud-db
  type: LoadBalancer
status:
  loadBalancer: {}
