#ConfigMap for the username
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-username
data:
  username: root
---
#Secret to be used to access the database
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-password
data:
  password: cm9vdA==
type: Opaque
---
#Creation of the Persistent Volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#Deployment of the database itself
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-cloud-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-cloud-db
  template:
    metadata:
      labels:
        app: mongo-cloud-db
        selector: mongo-cloud-db
    spec:
      containers:
      - name: mongo-cloud-db
        image: mongo:4
        args: ["--dbpath","/data/db"]
        livenessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongodb-username
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-password
                key: password
        volumeMounts:
        - name: "mongo-data-dir"
          mountPath: "/data/db"
      volumes:
      - name: "mongo-data-dir"
        persistentVolumeClaim:
          claimName: "mongo-data"
