# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\"$\n\x14\x41\x63\x63ountMusicResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\"@\n\x18\x41\x63\x63ountMusicListResponse\x12$\n\x05music\x18\x01 \x03(\x0b\x32\x15.AccountMusicResponse\"=\n\x16GetMusicRequestAccount\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tmusicname\x18\x02 \x01(\t\"\x1a\n\x07Success\x12\x0f\n\x07success\x18\x01 \x01(\x08\"z\n\x0cUserResponse\x12\x10\n\x08username\x18\x01 \x01(\t\x12.\n\x0blistenLater\x18\x02 \x01(\x0b\x32\x19.AccountMusicListResponse\x12(\n\x05likes\x18\x03 \x01(\x0b\x32\x19.AccountMusicListResponse\"\x1f\n\x0bUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"%\n\x11UpdateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"%\n\x11\x43reateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"%\n\x11\x44\x65leteUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x1c\n\x0eMusicIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x32\xde\x03\n\x07\x41\x63\x63ount\x12,\n\rGetUserByName\x12\x0c.UserRequest\x1a\r.UserResponse\x12/\n\nUpdateUser\x12\x12.UpdateUserRequest\x1a\r.UserResponse\x12*\n\nCreateUser\x12\x12.CreateUserRequest\x1a\x08.Success\x12*\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\x08.Success\x12#\n\tLoginUser\x12\x0c.UserRequest\x1a\x08.Success\x12$\n\nLogoutUser\x12\x0c.UserRequest\x1a\x08.Success\x12\x30\n\x0bListenLater\x12\x17.GetMusicRequestAccount\x1a\x08.Success\x12?\n\x14GetListenLaterMusics\x12\x0c.UserRequest\x1a\x19.AccountMusicListResponse\x12)\n\x04Like\x12\x17.GetMusicRequestAccount\x1a\x08.Success\x12\x33\n\x08GetLikes\x12\x0c.UserRequest\x1a\x19.AccountMusicListResponseb\x06proto3')



_ACCOUNTMUSICRESPONSE = DESCRIPTOR.message_types_by_name['AccountMusicResponse']
_ACCOUNTMUSICLISTRESPONSE = DESCRIPTOR.message_types_by_name['AccountMusicListResponse']
_GETMUSICREQUESTACCOUNT = DESCRIPTOR.message_types_by_name['GetMusicRequestAccount']
_SUCCESS = DESCRIPTOR.message_types_by_name['Success']
_USERRESPONSE = DESCRIPTOR.message_types_by_name['UserResponse']
_USERREQUEST = DESCRIPTOR.message_types_by_name['UserRequest']
_UPDATEUSERREQUEST = DESCRIPTOR.message_types_by_name['UpdateUserRequest']
_CREATEUSERREQUEST = DESCRIPTOR.message_types_by_name['CreateUserRequest']
_DELETEUSERREQUEST = DESCRIPTOR.message_types_by_name['DeleteUserRequest']
_MUSICIDREQUEST = DESCRIPTOR.message_types_by_name['MusicIdRequest']
AccountMusicResponse = _reflection.GeneratedProtocolMessageType('AccountMusicResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTMUSICRESPONSE,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:AccountMusicResponse)
  })
_sym_db.RegisterMessage(AccountMusicResponse)

AccountMusicListResponse = _reflection.GeneratedProtocolMessageType('AccountMusicListResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTMUSICLISTRESPONSE,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:AccountMusicListResponse)
  })
_sym_db.RegisterMessage(AccountMusicListResponse)

GetMusicRequestAccount = _reflection.GeneratedProtocolMessageType('GetMusicRequestAccount', (_message.Message,), {
  'DESCRIPTOR' : _GETMUSICREQUESTACCOUNT,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:GetMusicRequestAccount)
  })
_sym_db.RegisterMessage(GetMusicRequestAccount)

Success = _reflection.GeneratedProtocolMessageType('Success', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESS,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:Success)
  })
_sym_db.RegisterMessage(Success)

UserResponse = _reflection.GeneratedProtocolMessageType('UserResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERRESPONSE,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:UserResponse)
  })
_sym_db.RegisterMessage(UserResponse)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

UpdateUserRequest = _reflection.GeneratedProtocolMessageType('UpdateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEUSERREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:UpdateUserRequest)
  })
_sym_db.RegisterMessage(UpdateUserRequest)

CreateUserRequest = _reflection.GeneratedProtocolMessageType('CreateUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEUSERREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:CreateUserRequest)
  })
_sym_db.RegisterMessage(CreateUserRequest)

DeleteUserRequest = _reflection.GeneratedProtocolMessageType('DeleteUserRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEUSERREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:DeleteUserRequest)
  })
_sym_db.RegisterMessage(DeleteUserRequest)

MusicIdRequest = _reflection.GeneratedProtocolMessageType('MusicIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _MUSICIDREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:MusicIdRequest)
  })
_sym_db.RegisterMessage(MusicIdRequest)

_ACCOUNT = DESCRIPTOR.services_by_name['Account']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACCOUNTMUSICRESPONSE._serialized_start=17
  _ACCOUNTMUSICRESPONSE._serialized_end=53
  _ACCOUNTMUSICLISTRESPONSE._serialized_start=55
  _ACCOUNTMUSICLISTRESPONSE._serialized_end=119
  _GETMUSICREQUESTACCOUNT._serialized_start=121
  _GETMUSICREQUESTACCOUNT._serialized_end=182
  _SUCCESS._serialized_start=184
  _SUCCESS._serialized_end=210
  _USERRESPONSE._serialized_start=212
  _USERRESPONSE._serialized_end=334
  _USERREQUEST._serialized_start=336
  _USERREQUEST._serialized_end=367
  _UPDATEUSERREQUEST._serialized_start=369
  _UPDATEUSERREQUEST._serialized_end=406
  _CREATEUSERREQUEST._serialized_start=408
  _CREATEUSERREQUEST._serialized_end=445
  _DELETEUSERREQUEST._serialized_start=447
  _DELETEUSERREQUEST._serialized_end=484
  _MUSICIDREQUEST._serialized_start=486
  _MUSICIDREQUEST._serialized_end=514
  _ACCOUNT._serialized_start=517
  _ACCOUNT._serialized_end=995
# @@protoc_insertion_point(module_scope)
