# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import account_pb2 as account__pb2


class AccountStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUserByName = channel.unary_unary(
                '/Account/GetUserByName',
                request_serializer=account__pb2.UserRequest.SerializeToString,
                response_deserializer=account__pb2.UserResponse.FromString,
                )
        self.UpdateUser = channel.unary_unary(
                '/Account/UpdateUser',
                request_serializer=account__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=account__pb2.UserResponse.FromString,
                )
        self.CreateUser = channel.unary_unary(
                '/Account/CreateUser',
                request_serializer=account__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=account__pb2.Success.FromString,
                )
        self.DeleteUser = channel.unary_unary(
                '/Account/DeleteUser',
                request_serializer=account__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=account__pb2.Success.FromString,
                )
        self.LoginUser = channel.unary_unary(
                '/Account/LoginUser',
                request_serializer=account__pb2.UserRequest.SerializeToString,
                response_deserializer=account__pb2.Success.FromString,
                )
        self.LogoutUser = channel.unary_unary(
                '/Account/LogoutUser',
                request_serializer=account__pb2.UserRequest.SerializeToString,
                response_deserializer=account__pb2.Success.FromString,
                )
        self.ListenLater = channel.unary_unary(
                '/Account/ListenLater',
                request_serializer=account__pb2.GetMusicRequestAccount.SerializeToString,
                response_deserializer=account__pb2.Success.FromString,
                )
        self.GetListenLaterMusics = channel.unary_unary(
                '/Account/GetListenLaterMusics',
                request_serializer=account__pb2.UserRequest.SerializeToString,
                response_deserializer=account__pb2.AccountMusicListResponse.FromString,
                )
        self.Like = channel.unary_unary(
                '/Account/Like',
                request_serializer=account__pb2.GetMusicRequestAccount.SerializeToString,
                response_deserializer=account__pb2.Success.FromString,
                )
        self.GetLikes = channel.unary_unary(
                '/Account/GetLikes',
                request_serializer=account__pb2.UserRequest.SerializeToString,
                response_deserializer=account__pb2.AccountMusicListResponse.FromString,
                )


class AccountServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUserByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LogoutUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenLater(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetListenLaterMusics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Like(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLikes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccountServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUserByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByName,
                    request_deserializer=account__pb2.UserRequest.FromString,
                    response_serializer=account__pb2.UserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=account__pb2.UpdateUserRequest.FromString,
                    response_serializer=account__pb2.UserResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=account__pb2.CreateUserRequest.FromString,
                    response_serializer=account__pb2.Success.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=account__pb2.DeleteUserRequest.FromString,
                    response_serializer=account__pb2.Success.SerializeToString,
            ),
            'LoginUser': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginUser,
                    request_deserializer=account__pb2.UserRequest.FromString,
                    response_serializer=account__pb2.Success.SerializeToString,
            ),
            'LogoutUser': grpc.unary_unary_rpc_method_handler(
                    servicer.LogoutUser,
                    request_deserializer=account__pb2.UserRequest.FromString,
                    response_serializer=account__pb2.Success.SerializeToString,
            ),
            'ListenLater': grpc.unary_unary_rpc_method_handler(
                    servicer.ListenLater,
                    request_deserializer=account__pb2.GetMusicRequestAccount.FromString,
                    response_serializer=account__pb2.Success.SerializeToString,
            ),
            'GetListenLaterMusics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetListenLaterMusics,
                    request_deserializer=account__pb2.UserRequest.FromString,
                    response_serializer=account__pb2.AccountMusicListResponse.SerializeToString,
            ),
            'Like': grpc.unary_unary_rpc_method_handler(
                    servicer.Like,
                    request_deserializer=account__pb2.GetMusicRequestAccount.FromString,
                    response_serializer=account__pb2.Success.SerializeToString,
            ),
            'GetLikes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLikes,
                    request_deserializer=account__pb2.UserRequest.FromString,
                    response_serializer=account__pb2.AccountMusicListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Account', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Account(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUserByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/GetUserByName',
            account__pb2.UserRequest.SerializeToString,
            account__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/UpdateUser',
            account__pb2.UpdateUserRequest.SerializeToString,
            account__pb2.UserResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/CreateUser',
            account__pb2.CreateUserRequest.SerializeToString,
            account__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/DeleteUser',
            account__pb2.DeleteUserRequest.SerializeToString,
            account__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoginUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/LoginUser',
            account__pb2.UserRequest.SerializeToString,
            account__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LogoutUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/LogoutUser',
            account__pb2.UserRequest.SerializeToString,
            account__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenLater(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/ListenLater',
            account__pb2.GetMusicRequestAccount.SerializeToString,
            account__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetListenLaterMusics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/GetListenLaterMusics',
            account__pb2.UserRequest.SerializeToString,
            account__pb2.AccountMusicListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Like(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/Like',
            account__pb2.GetMusicRequestAccount.SerializeToString,
            account__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLikes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Account/GetLikes',
            account__pb2.UserRequest.SerializeToString,
            account__pb2.AccountMusicListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
