# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: artist.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='artist.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x61rtist.proto\"1\n\x0e\x41rtistResponse\x12\x11\n\tartist_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"6\n\x12\x41rtistListResponse\x12 \n\x07\x61rtists\x18\x01 \x03(\x0b\x32\x0f.ArtistResponse\"\\\n\x0eMusicResponses\x12\x10\n\x08music_id\x18\x01 \x01(\t\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.ChartTypes\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0f\n\x07streams\x18\x04 \x01(\x05\"5\n\x12MusicListResponses\x12\x1f\n\x06musics\x18\x01 \x03(\x0b\x32\x0f.MusicResponses\"%\n\x15GetArtistMusicRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"1\n\x1aGetArtistWithLetterRequest\x12\x13\n\x0bstring_char\x18\x01 \x01(\t\"%\n\x15GetTop20ArtistRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"\'\n\x17GetViral10ArtistRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t*/\n\nChartTypes\x12\n\n\x06Top200\x10\x00\x12\x0b\n\x07Viral50\x10\x01\x12\x08\n\x04\x42OTH\x10\x02\x32\x92\x02\n\x06\x41rtist\x12=\n\x0eGetArtistMusic\x12\x16.GetArtistMusicRequest\x1a\x13.MusicListResponses\x12G\n\x13GetArtistWithLetter\x12\x1b.GetArtistWithLetterRequest\x1a\x13.ArtistListResponse\x12=\n\x0eGetTop20Artist\x12\x16.GetTop20ArtistRequest\x1a\x13.ArtistListResponse\x12\x41\n\x10GetViral10Artist\x12\x18.GetViral10ArtistRequest\x1a\x13.ArtistListResponseb\x06proto3')
)

_CHARTTYPES = _descriptor.EnumDescriptor(
  name='ChartTypes',
  full_name='ChartTypes',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Top200', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Viral50', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BOTH', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=442,
  serialized_end=489,
)
_sym_db.RegisterEnumDescriptor(_CHARTTYPES)

ChartTypes = enum_type_wrapper.EnumTypeWrapper(_CHARTTYPES)
Top200 = 0
Viral50 = 1
BOTH = 2



_ARTISTRESPONSE = _descriptor.Descriptor(
  name='ArtistResponse',
  full_name='ArtistResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='artist_id', full_name='ArtistResponse.artist_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ArtistResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=65,
)


_ARTISTLISTRESPONSE = _descriptor.Descriptor(
  name='ArtistListResponse',
  full_name='ArtistListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='artists', full_name='ArtistListResponse.artists', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=121,
)


_MUSICRESPONSES = _descriptor.Descriptor(
  name='MusicResponses',
  full_name='MusicResponses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='music_id', full_name='MusicResponses.music_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='MusicResponses.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='MusicResponses.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='streams', full_name='MusicResponses.streams', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=215,
)


_MUSICLISTRESPONSES = _descriptor.Descriptor(
  name='MusicListResponses',
  full_name='MusicListResponses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='musics', full_name='MusicListResponses.musics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=217,
  serialized_end=270,
)


_GETARTISTMUSICREQUEST = _descriptor.Descriptor(
  name='GetArtistMusicRequest',
  full_name='GetArtistMusicRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GetArtistMusicRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=309,
)


_GETARTISTWITHLETTERREQUEST = _descriptor.Descriptor(
  name='GetArtistWithLetterRequest',
  full_name='GetArtistWithLetterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='string_char', full_name='GetArtistWithLetterRequest.string_char', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=311,
  serialized_end=360,
)


_GETTOP20ARTISTREQUEST = _descriptor.Descriptor(
  name='GetTop20ArtistRequest',
  full_name='GetTop20ArtistRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='GetTop20ArtistRequest.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=362,
  serialized_end=399,
)


_GETVIRAL10ARTISTREQUEST = _descriptor.Descriptor(
  name='GetViral10ArtistRequest',
  full_name='GetViral10ArtistRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='GetViral10ArtistRequest.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=440,
)

_ARTISTLISTRESPONSE.fields_by_name['artists'].message_type = _ARTISTRESPONSE
_MUSICRESPONSES.fields_by_name['type'].enum_type = _CHARTTYPES
_MUSICLISTRESPONSES.fields_by_name['musics'].message_type = _MUSICRESPONSES
DESCRIPTOR.message_types_by_name['ArtistResponse'] = _ARTISTRESPONSE
DESCRIPTOR.message_types_by_name['ArtistListResponse'] = _ARTISTLISTRESPONSE
DESCRIPTOR.message_types_by_name['MusicResponses'] = _MUSICRESPONSES
DESCRIPTOR.message_types_by_name['MusicListResponses'] = _MUSICLISTRESPONSES
DESCRIPTOR.message_types_by_name['GetArtistMusicRequest'] = _GETARTISTMUSICREQUEST
DESCRIPTOR.message_types_by_name['GetArtistWithLetterRequest'] = _GETARTISTWITHLETTERREQUEST
DESCRIPTOR.message_types_by_name['GetTop20ArtistRequest'] = _GETTOP20ARTISTREQUEST
DESCRIPTOR.message_types_by_name['GetViral10ArtistRequest'] = _GETVIRAL10ARTISTREQUEST
DESCRIPTOR.enum_types_by_name['ChartTypes'] = _CHARTTYPES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ArtistResponse = _reflection.GeneratedProtocolMessageType('ArtistResponse', (_message.Message,), dict(
  DESCRIPTOR = _ARTISTRESPONSE,
  __module__ = 'artist_pb2'
  # @@protoc_insertion_point(class_scope:ArtistResponse)
  ))
_sym_db.RegisterMessage(ArtistResponse)

ArtistListResponse = _reflection.GeneratedProtocolMessageType('ArtistListResponse', (_message.Message,), dict(
  DESCRIPTOR = _ARTISTLISTRESPONSE,
  __module__ = 'artist_pb2'
  # @@protoc_insertion_point(class_scope:ArtistListResponse)
  ))
_sym_db.RegisterMessage(ArtistListResponse)

MusicResponses = _reflection.GeneratedProtocolMessageType('MusicResponses', (_message.Message,), dict(
  DESCRIPTOR = _MUSICRESPONSES,
  __module__ = 'artist_pb2'
  # @@protoc_insertion_point(class_scope:MusicResponses)
  ))
_sym_db.RegisterMessage(MusicResponses)

MusicListResponses = _reflection.GeneratedProtocolMessageType('MusicListResponses', (_message.Message,), dict(
  DESCRIPTOR = _MUSICLISTRESPONSES,
  __module__ = 'artist_pb2'
  # @@protoc_insertion_point(class_scope:MusicListResponses)
  ))
_sym_db.RegisterMessage(MusicListResponses)

GetArtistMusicRequest = _reflection.GeneratedProtocolMessageType('GetArtistMusicRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETARTISTMUSICREQUEST,
  __module__ = 'artist_pb2'
  # @@protoc_insertion_point(class_scope:GetArtistMusicRequest)
  ))
_sym_db.RegisterMessage(GetArtistMusicRequest)

GetArtistWithLetterRequest = _reflection.GeneratedProtocolMessageType('GetArtistWithLetterRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETARTISTWITHLETTERREQUEST,
  __module__ = 'artist_pb2'
  # @@protoc_insertion_point(class_scope:GetArtistWithLetterRequest)
  ))
_sym_db.RegisterMessage(GetArtistWithLetterRequest)

GetTop20ArtistRequest = _reflection.GeneratedProtocolMessageType('GetTop20ArtistRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETTOP20ARTISTREQUEST,
  __module__ = 'artist_pb2'
  # @@protoc_insertion_point(class_scope:GetTop20ArtistRequest)
  ))
_sym_db.RegisterMessage(GetTop20ArtistRequest)

GetViral10ArtistRequest = _reflection.GeneratedProtocolMessageType('GetViral10ArtistRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETVIRAL10ARTISTREQUEST,
  __module__ = 'artist_pb2'
  # @@protoc_insertion_point(class_scope:GetViral10ArtistRequest)
  ))
_sym_db.RegisterMessage(GetViral10ArtistRequest)



_ARTIST = _descriptor.ServiceDescriptor(
  name='Artist',
  full_name='Artist',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=492,
  serialized_end=766,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetArtistMusic',
    full_name='Artist.GetArtistMusic',
    index=0,
    containing_service=None,
    input_type=_GETARTISTMUSICREQUEST,
    output_type=_MUSICLISTRESPONSES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetArtistWithLetter',
    full_name='Artist.GetArtistWithLetter',
    index=1,
    containing_service=None,
    input_type=_GETARTISTWITHLETTERREQUEST,
    output_type=_ARTISTLISTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTop20Artist',
    full_name='Artist.GetTop20Artist',
    index=2,
    containing_service=None,
    input_type=_GETTOP20ARTISTREQUEST,
    output_type=_ARTISTLISTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetViral10Artist',
    full_name='Artist.GetViral10Artist',
    index=3,
    containing_service=None,
    input_type=_GETVIRAL10ARTISTREQUEST,
    output_type=_ARTISTLISTRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ARTIST)

DESCRIPTOR.services_by_name['Artist'] = _ARTIST

# @@protoc_insertion_point(module_scope)
